# coding: utf-8

"""
    PUBLIC - VVCLI Restfull API

    The public API allows users to authenticate to access accounts and contracts, as well as manage Object Storage contracts. With a focus on creating S3 credentials for users and sub-users, the solution simplifies resource management by providing an integrated and intuitive experience.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vvcli_sdk.models.new_user_obj_storage_schema import NewUserObjStorageSchema


class TestNewUserObjStorageSchema(unittest.TestCase):
    """NewUserObjStorageSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewUserObjStorageSchema:
        """Test NewUserObjStorageSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `NewUserObjStorageSchema`
        """
        model = NewUserObjStorageSchema()
        if include_optional:
            return NewUserObjStorageSchema(
                user_srn = '',
                contract_key = '',
                client_id = '',
                keys = [
                    vvcli_sdk.models.credential_key.CredentialKey(
                        access_key = '', 
                        secret_key = '', )
                    ]
            )
        else:
            return NewUserObjStorageSchema(
                user_srn = '',
                contract_key = '',
                client_id = '',
        )
        """

    def testNewUserObjStorageSchema(self):
        """Test NewUserObjStorageSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
