# coding: utf-8

"""
    PUBLIC - VVCLI Restfull API

    The public API allows users to authenticate to access accounts and contracts, as well as manage Object Storage contracts. With a focus on creating S3 credentials for users and sub-users, the solution simplifies resource management by providing an integrated and intuitive experience.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vvcli_sdk.models.auth_info_schema import AuthInfoSchema


class TestAuthInfoSchema(unittest.TestCase):
    """AuthInfoSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthInfoSchema:
        """Test AuthInfoSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `AuthInfoSchema`
        """
        model = AuthInfoSchema()
        if include_optional:
            return AuthInfoSchema(
                clerk_id = '',
                srn = '',
                email = '',
                nickname = ''
            )
        else:
            return AuthInfoSchema(
                clerk_id = '',
                srn = '',
                email = '',
                nickname = '',
        )
        """

    def testAuthInfoSchema(self):
        """Test AuthInfoSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
