# coding: utf-8

"""
    PUBLIC - VVCLI Restfull API

    The public API allows users to authenticate to access accounts and contracts, as well as manage Object Storage contracts. With a focus on creating S3 credentials for users and sub-users, the solution simplifies resource management by providing an integrated and intuitive experience.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vvcli_sdk.models.page_account_schema import PageAccountSchema


class TestPageAccountSchema(unittest.TestCase):
    """PageAccountSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageAccountSchema:
        """Test PageAccountSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PageAccountSchema`
        """
        model = PageAccountSchema()
        if include_optional:
            return PageAccountSchema(
                items = [
                    vvcli_sdk.models.account_schema.AccountSchema(
                        uuid = '', 
                        client_id = 56, 
                        client_name = '', 
                        client_status = '', )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0
            )
        else:
            return PageAccountSchema(
                items = [
                    vvcli_sdk.models.account_schema.AccountSchema(
                        uuid = '', 
                        client_id = 56, 
                        client_name = '', 
                        client_status = '', )
                    ],
                page = 1.0,
                size = 1.0,
        )
        """

    def testPageAccountSchema(self):
        """Test PageAccountSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
