# coding: utf-8

"""
    PUBLIC - VVCLI Restfull API

    The public API allows users to authenticate to access accounts and contracts, as well as manage Object Storage contracts. With a focus on creating S3 credentials for users and sub-users, the solution simplifies resource management by providing an integrated and intuitive experience.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vvcli_sdk.models.access_permissions import AccessPermissions


class TestAccessPermissions(unittest.TestCase):
    """AccessPermissions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessPermissions(self):
        """Test AccessPermissions"""
        # inst = AccessPermissions()


if __name__ == "__main__":
    unittest.main()
