# coding: utf-8

"""
    PUBLIC - Gravscale Public Restful API

    API pública da Gravscale oferece aos usuários a capacidade de se autenticar, visualizar e contratar produtos disponíveis, enviar dados de contratação, escolher formas de pagamento e gerenciar nossos produtos. Além disso, os usuários podem cadastrar chaves SSH e realizar o deploy de um sistema operacional de forma eficiente e segura. Esta API foi projetado para simplificar e agilizar o gerenciamento de recursos proporcionando que a a Gravscale forneça uma experiência integrada e intuitiva para os usuários.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vvcli_sdk.models.page_get_sub_user_obj_storage_schema import (
    PageGetSubUserObjStorageSchema,
)


class TestPageGetSubUserObjStorageSchema(unittest.TestCase):
    """PageGetSubUserObjStorageSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageGetSubUserObjStorageSchema:
        """Test PageGetSubUserObjStorageSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PageGetSubUserObjStorageSchema`
        """
        model = PageGetSubUserObjStorageSchema()
        if include_optional:
            return PageGetSubUserObjStorageSchema(
                items = [
                    vvcli_sdk.models.get_sub_user_obj_storage_schema.GetSubUserObjStorageSchema(
                        user_srn = '', 
                        display_name = '', 
                        client_id = '', )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0
            )
        else:
            return PageGetSubUserObjStorageSchema(
                items = [
                    vvcli_sdk.models.get_sub_user_obj_storage_schema.GetSubUserObjStorageSchema(
                        user_srn = '', 
                        display_name = '', 
                        client_id = '', )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
        )
        """

    def testPageGetSubUserObjStorageSchema(self):
        """Test PageGetSubUserObjStorageSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
