# coding: utf-8

"""
    PUBLIC - VVCLI Restfull API

    The public API allows users to authenticate to access accounts and contracts, as well as manage Object Storage contracts. With a focus on creating S3 credentials for users and sub-users, the solution simplifies resource management by providing an integrated and intuitive experience.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vvcli_sdk.api.object_storage_api import ObjectStorageApi


class TestObjectStorageApi(unittest.TestCase):
    """ObjectStorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectStorageApi()

    def tearDown(self) -> None:
        pass

    def test_create_client_user(self) -> None:
        """Test case for create_client_user

        Create Client User Object Storage
        """
        pass

    def test_create_subuser(self) -> None:
        """Test case for create_subuser

        Create Subuser Object Storage
        """
        pass

    def test_get_client_user(self) -> None:
        """Test case for get_client_user

        Get Client User Object Storage
        """
        pass

    def test_get_subusers(self) -> None:
        """Test case for get_subusers

        Get Subusers Object Storage
        """
        pass


if __name__ == "__main__":
    unittest.main()
