# coding: utf-8

"""
    PUBLIC - Gravscale Public Restful API

    API pública da Gravscale oferece aos usuários a capacidade de se autenticar, visualizar e contratar produtos disponíveis, enviar dados de contratação, escolher formas de pagamento e gerenciar nossos produtos. Além disso, os usuários podem cadastrar chaves SSH e realizar o deploy de um sistema operacional de forma eficiente e segura. Esta API foi projetado para simplificar e agilizar o gerenciamento de recursos proporcionando que a a Gravscale forneça uma experiência integrada e intuitiva para os usuários.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vvcli_sdk.api.object_storage_api import ObjectStorageApi


class TestObjectStorageApi(unittest.TestCase):
    """ObjectStorageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ObjectStorageApi()

    def tearDown(self) -> None:
        pass

    def test_create_client_user(self) -> None:
        """Test case for create_client_user

        Create Client User Object Storage
        """
        pass

    def test_create_subuser(self) -> None:
        """Test case for create_subuser

        Create Subuser Object Storage
        """
        pass

    def test_get_client_user(self) -> None:
        """Test case for get_client_user

        Get Client User Object Storage
        """
        pass

    def test_get_subusers(self) -> None:
        """Test case for get_subusers

        Get Subusers Object Storage
        """
        pass


if __name__ == "__main__":
    unittest.main()
