# coding: utf-8

"""
    PUBLIC - Gravscale Public Restful API

    API pública da Gravscale oferece aos usuários a capacidade de se autenticar, visualizar e contratar produtos disponíveis, enviar dados de contratação, escolher formas de pagamento e gerenciar nossos produtos. Além disso, os usuários podem cadastrar chaves SSH e realizar o deploy de um sistema operacional de forma eficiente e segura. Esta API foi projetado para simplificar e agilizar o gerenciamento de recursos proporcionando que a a Gravscale forneça uma experiência integrada e intuitiva para os usuários.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vvcli_sdk.models.page_account_schema import PageAccountSchema

class TestPageAccountSchema(unittest.TestCase):
    """PageAccountSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageAccountSchema:
        """Test PageAccountSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PageAccountSchema`
        """
        model = PageAccountSchema()
        if include_optional:
            return PageAccountSchema(
                items = [
                    vvcli_sdk.models.account_schema.AccountSchema(
                        uuid = '', 
                        client_id = 56, 
                        client_name = '', 
                        client_status = '', )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
                pages = 0.0
            )
        else:
            return PageAccountSchema(
                items = [
                    vvcli_sdk.models.account_schema.AccountSchema(
                        uuid = '', 
                        client_id = 56, 
                        client_name = '', 
                        client_status = '', )
                    ],
                total = 0.0,
                page = 1.0,
                size = 1.0,
        )
        """

    def testPageAccountSchema(self):
        """Test PageAccountSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
