# coding: utf-8

"""
    PUBLIC - VVCLI Restfull API

    The public API allows users to authenticate to access accounts and contracts, as well as manage Object Storage contracts. With a focus on creating S3 credentials for users and sub-users, the solution simplifies resource management by providing an integrated and intuitive experience.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vvcli_sdk.models.new_sub_user_obj_storage_schema import NewSubUserObjStorageSchema


class TestNewSubUserObjStorageSchema(unittest.TestCase):
    """NewSubUserObjStorageSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewSubUserObjStorageSchema:
        """Test NewSubUserObjStorageSchema
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `NewSubUserObjStorageSchema`
        """
        model = NewSubUserObjStorageSchema()
        if include_optional:
            return NewSubUserObjStorageSchema(
                user_srn = '',
                display_name = '',
                client_id = '',
                keys = [
                    vvcli_sdk.models.credential_key.CredentialKey(
                        access_key = '', 
                        secret_key = '', )
                    ]
            )
        else:
            return NewSubUserObjStorageSchema(
                user_srn = '',
                display_name = '',
                client_id = '',
        )
        """

    def testNewSubUserObjStorageSchema(self):
        """Test NewSubUserObjStorageSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
