[project]
name = "vvcli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.36.6",
    "icecream>=2.1.4",
    "tabulate>=0.9.0",
    "typer>=0.15.1",
]
