# coding: utf-8

# flake8: noqa
"""
    PUBLIC - VVCLI Restfull API

    The public API allows users to authenticate to access accounts and contracts, as well as manage Object Storage contracts. With a focus on creating S3 credentials for users and sub-users, the solution simplifies resource management by providing an integrated and intuitive experience.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from vvcli_sdk.models.access_permissions import AccessPermissions
from vvcli_sdk.models.account_schema import AccountSchema
from vvcli_sdk.models.add_bucket_quota_schema import AddBucketQuotaSchema
from vvcli_sdk.models.auth_info_schema import AuthInfoSchema
from vvcli_sdk.models.contract_schema import ContractSchema
from vvcli_sdk.models.create_bucket_obj_storage_schema import (
    CreateBucketObjStorageSchema,
)
from vvcli_sdk.models.create_sub_user_obj_storage_schema import (
    CreateSubUserObjStorageSchema,
)
from vvcli_sdk.models.credential_key import CredentialKey
from vvcli_sdk.models.get_bucket_obj_storage_schema import GetBucketObjStorageSchema
from vvcli_sdk.models.get_bucket_quota_schema import GetBucketQuotaSchema
from vvcli_sdk.models.get_bucket_usage_schema import GetBucketUsageSchema
from vvcli_sdk.models.get_sub_user_obj_storage_schema import GetSubUserObjStorageSchema
from vvcli_sdk.models.get_user_obj_storage_schema import GetUserObjStorageSchema
from vvcli_sdk.models.http_validation_error import HTTPValidationError
from vvcli_sdk.models.new_sub_user_obj_storage_schema import NewSubUserObjStorageSchema
from vvcli_sdk.models.new_user_obj_storage_schema import NewUserObjStorageSchema
from vvcli_sdk.models.page_account_schema import PageAccountSchema
from vvcli_sdk.models.page_contract_schema import PageContractSchema
from vvcli_sdk.models.page_get_bucket_obj_storage_schema import (
    PageGetBucketObjStorageSchema,
)
from vvcli_sdk.models.page_get_sub_user_obj_storage_schema import (
    PageGetSubUserObjStorageSchema,
)
from vvcli_sdk.models.user_quota_obj_storage_schema import UserQuotaObjStorageSchema
from vvcli_sdk.models.user_usage_obj_storage_schema import UserUsageObjStorageSchema
from vvcli_sdk.models.validation_error import ValidationError
from vvcli_sdk.models.validation_error_loc_inner import ValidationErrorLocInner
