# coding: utf-8

"""
    PUBLIC - VVCLI Restfull API

    The public API allows users to authenticate to access accounts and contracts, as well as manage Object Storage contracts. With a focus on creating S3 credentials for users and sub-users, the solution simplifies resource management by providing an integrated and intuitive experience.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AccessPermissions(str, Enum):
    """
    AccessPermissions
    """

    """
    allowed enum values
    """
    READ = "read"
    WRITE = "write"
    READWRITE = "readwrite"
    FULL = "full"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccessPermissions from a JSON string"""
        return cls(json.loads(json_str))
