# coding: utf-8

"""
    PUBLIC - Gravscale Public Restful API

    API pública da Gravscale oferece aos usuários a capacidade de se autenticar, visualizar e contratar produtos disponíveis, enviar dados de contratação, escolher formas de pagamento e gerenciar nossos produtos. Além disso, os usuários podem cadastrar chaves SSH e realizar o deploy de um sistema operacional de forma eficiente e segura. Esta API foi projetado para simplificar e agilizar o gerenciamento de recursos proporcionando que a a Gravscale forneça uma experiência integrada e intuitiva para os usuários.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AccessPermissions(str, Enum):
    """
    AccessPermissions
    """

    """
    allowed enum values
    """
    READ = 'read'
    WRITE = 'write'
    READWRITE = 'readwrite'
    FULL = 'full'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccessPermissions from a JSON string"""
        return cls(json.loads(json_str))


